# Generated by Django 3.0.2 on 2020-11-04 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_made', models.DateField()),
                ('tracking', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
