# Generated by Django 3.0.2 on 2020-11-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockprediction', '0002_auto_20201125_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='prediction',
            name='ticker',
            field=models.CharField(max_length=50),
        ),
    ]
