# Generated by Django 3.0.2 on 2020-11-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockprediction', '0003_auto_20201130_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediction',
            old_name='current_price',
            new_name='prediction',
        ),
    ]
