# Generated by Django 3.1.5 on 2021-01-28 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='tracked_by',
            field=models.ManyToManyField(blank=True, related_name='tracking', to=settings.AUTH_USER_MODEL),
        ),
    ]
