# Generated by Django 3.0.2 on 2021-03-01 06:18

from django.db import migrations
import csv

def initialize_stocks(apps, SchemaEditor):
    #Get stock model, uses historical registry 'apps' to do so
    #May access older version of 'Stock' but shouldnt matter
    Stock = apps.get_model('stocks', 'Stock')
    Stock.objects.all().delete() #Delete any stocks already in there to reinitialize properly
    #Get the company info
    filename =  'companylist.csv'
    fields = []
    #Go through companylist
    with open(filename, 'r') as f:
        f_reader = csv.reader(f)
        fields = next(f_reader) # Get rid of first row basically
        for row in f_reader:
            ticker = row[0] #Ticker is first in row
            name = row[1] #Name is second in row
            Stock.objects.create(ticker=ticker, company_name=name)



class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_stocks)
    ]
