# Generated by Django 3.1.5 on 2021-01-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_tracked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
