# Generated by Django 3.1.5 on 2021-03-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='dummy2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
