# Generated by Django 3.1.5 on 2021-02-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_company_name'),
        ('stocks', '0002_auto_20210217_1927'),
    ]

    operations = [
    ]
