# Generated by Django 3.1.5 on 2021-03-01 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210217_1927'),
        ('stocks', '0003_stock_company_name'),
    ]

    operations = [
    ]
