# Generated by Django 3.1.7 on 2021-02-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_merge_20210228_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
